services:
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2
      - app3

  app1:
    container_name: app1
    build:
      context: app
    ports:
      - "5000:5000"
    networks:
      - backend

  app2:
    container_name: app2
    build:
      context: app
    ports:
      - "5001:5001"
    networks:
      - backend

  app3:
    container_name: app3
    build:
      context: app
    ports:
      - "5002:5002"
    networks:
      - backend

networks:
  backend:
    driver: bridge
